= Конституция (Основной Закон) Российской Социалистической Федеративной Советской Республики (РСФСР)

== Раздел первый. Декларация прав трудящегося и эксплоатируемого народа

=== Глава первая

==== Статья 1

Россия объявляется Республикой Советов, Рабочих, Солдатских и Крестьянских Депутатов.
Вся власть в центре и на местах принадлежит этим советам.

==== Статья 2

Российская Советская Республика учреждается на основе свободного союза свободных наций, как федерация Советских национальных республик.

=== Глава вторая

==== Статья 3

Ставя своей основной задачей уничтожение всякой эксплоатации человека человеком, полное устранение деления общества на классы, беспощадное подавление эксплоататоров, установление социалистической организации общества и победы социализма во всех странах, III Всероссийский Съезд Советов Рабочих, Солдатских и Крестьянских Депутатов постановляет далее:

. В осуществление социализации земли частная собственность на землю отменяется и весь земельный фонд объявляется общенародным достоянием и передается трудящимся без всякого выкупа, на началах уравнительного землепользования.
. Все леса, недра и воды общегосударственного значения, а равно и весь живой и мертвый инвентарь, образцовые поместья и сельско-хозяйственные предприятия объявляются национальным достоянием.
. Как первый шаг к полному переходу фабрик, заводов, рудников, железных дорог, прочих средств производства и транспорта в собственность Советской Рабоче-Крестьянской Республики, подтверждается Советский закон о рабочем контроле и о Высшем Совете Народного Хозяйства в целях обеспечения власти трудящихся над эксплоататорами.
. III Всероссийский Съезд Советов рассматривает Советский закон об аннулировании (уничтожении) займов, заключенных правительством царя, помещиков и буржуазии, как первый удар международному банковому, финансовому капиталу, выражая уверенность, что Советская власть пойдет твердо по этому пути вплоть до полной победы международного рабочего восстания против ига капитала.
. Подтверждается переход всех банков в собственность Рабоче-Крестьянского государства, как одно из условий освобождения трудящихся масс из-под ига капитала.
. В целях уничтожения паразитических слоев общества и организации хозяйства вводится всеобщая трудовая повинность.
. В интересах обеспечения всей полноты власти за трудящимися массами и устранения всякой возможности восстановления власти эксплоататоров декретируется вооружение трудящихся, образование Социалистической Красной Армии рабочих и крестьян и полное разоружение имущих классов.

=== Глава третья

==== Статья 4

Выражая непреклонную решимость вырвать человечество из когтей финансового капитала и империализма, заливших землю кровью в настоящей преступнейшей из всех войн, III Всероссийский Съезд Советов всецело присоединяется к проводимой Советской властью политике разрыва тайных договоров, организации самого широкого братания с рабочими и крестьянами воюющих ныне между собой армий и достижения во что бы то ни стало революционными мерами демократического мира трудящихся без аннексий и контрибуций, на основе свободного самоопределения наций.

==== Статья 5

В тех же целях III Всероссийский Съезд Советов настаивает на полном разрыве с варварской политикой буржуазной цивилизации, строившей благосостояние эксплоататоров в немногих избранных нациях на порабощении сотен миллионов трудящегося населения в Азии, в колониях вообще и в малых странах.

==== Статья 6

III Всероссийский Съезд Советов приветствует политику Совета Народных Комиссаров, провозгласившего полную независимость Финляндии, начавшего вывод войск из Персии, объявившего свободу самоопределения Армении.

=== Глава четвертая

==== Статья 7

III Всероссийский Съезд Советов Рабочих, Солдатских и Крестьянских Депутатов полагает, что теперь, в момент решительной борьбы пролетариата с его эксплоататорами, эксплоататорам не может быть места ни в одном из органов власти.
Власть должна принадлежать целиком и исключительно трудящимся массам и их полномочному представительству - Советам Рабочих, Солдатских и Крестьянских Депутатов.

==== Статья 8

Вместе с тем, стремясь создать действительно свободный и добровольный, а, следовательно тем более полный и прочный, союз трудящихся классов всех наций России, III Всероссийский Съезд Советов ограничивается установлением коренных начал федерации Советских Республик России, предоставляя рабочим и крестьянам каждой нации принять самостоятельное решение на своем собственном полномочном Советском съезде: желают ли они и на каких основаниях участвовать в федеральном правительстве и в остальных федеральных Советских учреждениях.

== Раздел второй. Общие положения Конституции Российской Социалистической Федеративной Советской Республики

=== Глава пятая

==== Статья 9

Основная задача рассчитанной на настоящий переходный момент Конституции Российской Социалистической Федеративной Советской Республики заключается в установлении диктатуры городского и сельского пролетариата и беднейшего крестьянства в виде мощной Всероссийской Советской власти в целях полного подавления буржуазии, уничтожения эксплоатации человека человеком и водворения социализма, при котором не будет ни деления на классы, ни государственной власти.

==== Статья 10

Российская Республика есть свободное социалистическое общество всех трудящихся России.
Вся власть в пределах Российской Социалистической Федеративной Советской Республики принадлежит всему рабочему населению страны, объединенному в городских и сельских Советах.

==== Статья 11

Советы областей, отличающихся особым бытом и национальным составом, могут объединиться в автономные областные союзы, во главе которых, как и во главе всяких могущих быть образованными областных объединений вообще, стоят областные Съезды Советов и их исполнительные органы.
Эти автономные областные союзы входят на началах федерации в Российскую Социалистическую Федеративную Советскую Республику.

==== Статья 12

Верховная власть в Российской Социалистической Федеративной Советской Республике принадлежит Всероссийскому Съезду Советов, а в период между Съездами - Всероссийскому Центральному Исполнительному Комитету Советов.

==== Статья 13

В целях обеспечения за трудящимися действительной свободы совести церковь отделяется от государства и школа от церкви, а свобода религиозной и антирелигиозной пропаганды признается за всеми гражданами.

==== Статья 14

В целях обеспечения за трудящимися действительной свободы выражения своих мнений Российская Социалистическая Федеративная Советская Республика уничтожает зависимость печати от капитала и предоставляет в руки рабочего класса и крестьянской бедноты все технические и материальные средства к изданию газет, брошюр, книг и всяких других произведений печати и обеспечивает их свободное распространение по всей стране.

==== Статья 15

В целях обеспечения за трудящимися действительной свободы собраний Российская Социалистическая Федеративная Советская Республика, признавая право граждан Советской Республики свободно устраивать собрания, митинги, шествия и т.п., предоставляет в распоряжение рабочего класса и крестьянской бедноты все пригодные для устройства народных собраний помещения с обстановкой, освещением и отоплением.

==== Статья 16

В целях обеспечения за трудящимися действительной свободы союзов Российская Социалистическая Федеративная Советская Республика, сломив экономическую и политическую власть имущих классов и этим устранив все препятствия, которые до сих пор мешали в буржуазном обществе рабочим и крестьянам пользоваться свободой организации и действия, оказывает рабочим и беднейшим крестьянам всяческое содействие, материальное и иное, для их объединения и организации.

==== Статья 17

В целях обеспечения за трудящимися действительного доступа к знанию Российская Социалистическая Федеративная Советская Республика ставит своей задачей предоставить рабочим и беднейшим крестьянам полное, всестороннее и бесплатное образование.

==== Статья 18

Российская Социалистическая Федеративная Советская Республика признает труд обязанностью всех граждан Республики и провозглашает лозунг: "Не трудящийся да не ест".

==== Статья 19

В целях всемерной охраны завоеваний Великой Рабоче-Крестьянской Революции Российская Социалистическая Федеративная Советская Республика признает обязанностью всех граждан Республики защиту социалистического отечества и устанавливает всеобщую воинскую повинность.

Почетное право защищать революцию с оружием в руках предоставляется только трудящимся; на нетрудовые же элементы возлагается отправление иных военных обязанностей.

==== Статья 20

Исходя из солидарности трудящихся всех наций, Российская Социалистическая Федеративная Советская Республика предоставляет все политические права российских граждан иностранцам, проживающим на территории Российской Республики для трудовых занятий и принадлежащим к рабочему классу или к непользующемуся чужим трудом крестьянству, и признает за местными Советами право предоставлять таким иностранцам, без всяких затруднительных формальностей, права российского гражданства.

==== Статья 21

Российская Социалистическая Федеративная Советская Республика предоставляет право убежища всем иностранцам, подвергающимся преследованию за политические и религиозные преступления.

==== Статья 22

Российская Социалистическая Федеративная Советская Республика, признавая равные права за гражданами независимо от их расовой и национальной принадлежности, объявляет противоречащим основным законам Республики установление или допущение каких-либо привилегий или преимуществ на этом основании, а равно какое бы то ни было угнетение национальных меньшинств или ограничение их равноправия.

==== Статья 23

Руководствуясь интересами рабочего класса в целом, Российская Социалистическая Федеративная Советская Республика лишает отдельных лиц и отдельные группы прав, которые пользуются ими в ущерб интересам социалистической революции.

== Раздел третий. Конструкция Советской власти

=== Организация центральной власти

==== Глава шестая. О Всероссийском Съезде Советов Рабочих, Крестьянских, Красноармейских и Казачьих Депутатов

===== Статья 24

Всероссийский Съезд Советов является высшей властью Российской Социалистической Федеративной Советской Республики.

===== Статья 25

Всероссийский Съезд Советов составляется из представителей городских Советов, по расчету 1 депутат на 25.000 избирателей, и представителей губернских Съездов Советов, по расчету 1 депутат на 125.000 жителей.

*Примечание 1.* В случае, если губернский Съезд Советов не предшествует Всероссийскому Съезду Советов, то делегаты на последний посылаются непосредственно уездными Съездами Советов.

*Примечание 2.* В случае, если областной Съезд Советов непосредственно предшествует Всероссийскому Съезду Советов, то делегаты на последний могут быть посланы областным Съездом Советов.

===== Статья 26

Всероссийский Съезд Советов созывается Всероссийским Центральным Исполнительным Комитетом Советов не реже двух раз в год.

===== Статья 27

Чрезвычайный Всероссийский Съезд Советов созывается Всероссийским Центральным Исполнительным Комитетом Советов по собственному почину или по требованию Советов местностей, насчитывающих не менее 1/3 всего населения Республики.

===== Статья 28

Всероссийский Съезд Советов избирает Всероссийский Центральный Исполнительный Комитет Советов в числе не свыше 200 человек.

===== Статья 29

Всероссийский Центральный Исполнительный Комитет Советов всецело ответственен перед Всероссийским Съездом Советов.

===== Статья 30

В период между Съездами высшей властью Республики является Всероссийский Центральный Исполнительный Комитет Советов.

==== Глава седьмая. О Всероссийском Центральном Исполнительном Комитете Советов

===== Статья 31

Всероссийский Центральный Исполнительный Комитет Советов является высшим законодательным, распорядительным и контролирующим органом Российской Социалистической Федеративной Советской Республики.

===== Статья 32

Всероссийский Центральный Исполнительный Комитет Советов дает общее направление деятельности Рабоче-Крестьянского Правительства и всех органов Советской власти в стране, объединяет и согласует работы по законодательству и управлению и наблюдает за проведением в жизнь Советской Конституции, постановлений Всероссийских Съездов Советов и центральных органов Советской власти.

===== Статья 33

Всероссийский Центральный Исполнительный Комитет Советов рассматривает и утверждает проекты декретов и иные предложения, вносимые Советом Народных Комиссаров или отдельными ведомствами, а также издает собственные декреты и распоряжения.

===== Статья 34

Всероссийский Центральный Исполнительный Комитет Советов созывает Всероссийский Съезд Советов, которому представляет отчет о своей деятельности и доклады по общей политике и отдельным вопросам.

===== Статья 35

Всероссийский Центральный Исполнительный Комитет Советов образует Совет Народных Комиссаров для общего управления делами Российской Социалистической Федеративной Советской Республики и отделы (Народные Комиссариаты) для руководства отдельными отраслями управления.

===== Статья 36

Члены Всероссийского Центрального Исполнительного Комитета Советов работают в отделах (Народных Комиссариатах) или выполняют особые поручения Всероссийского Центрального Исполнительного Комитета Советов.

==== Глава восьмая. О Совете Народных Комиссаров

===== Статья 37

Совету Народных Комиссаров принадлежит общее управление делами Российской Социалистической Федеративной Советской Республики.

===== Статья 38

В осуществление этой задачи Совет Народных Комиссаров издает декреты, распоряжения, инструкции и вообще принимает все меры, необходимые для правильного и быстрого течения государственной жизни.

===== Статья 39

О всех своих постановлениях и решениях Совет Народных Комиссаров немедленно сообщает Всероссийскому Центральному Исполнительному Комитету Советов.

===== Статья 40

Всероссийский Центральный Исполнительный Комитет Советов вправе отменить или приостановить всякое постановление или решение Совета Народных Комиссаров.

===== Статья 41

Все постановления и решения Совета Народных Комиссаров, имеющие крупное общеполитическое значение, представляются на рассмотрение и утверждение Всероссийского Центрального Исполнительного Комитета Советов.

*Примечание.* Мероприятия, требующие неотложного выполнения, могут быть осуществлены Советом Народных Комиссаров непосредственно.

===== Статья 42

Члены Совета Народных Комиссаров стоят во главе отдельных Народных Комиссариатов.

===== Статья 43

Народных Комиссариатов образуется 18, а именно:

. по Иностранным Делам;
. по Военным Делам;
. по Морским Делам;
. по Внутренним Делам;
. Юстиции;
. Труда;
. Социального Обеспечения;
. Просвещения;
. Почт и Телеграфов;
. по Делам Национальностей;
. по Финансовым Делам;
. Путей Сообщения;
. Земледелия;
. Торговли и Промышленности;
. Продовольствия;
. Государственного Контроля;
. Высший Совет Народного Хозяйства;
. Здравоохранения.

===== Статья 44

При каждом Народном Комиссаре, под его председательством, образуется коллегия, члены которой утверждаются Советом Народных Комиссаров.

===== Статья 45

Народный Комиссар вправе единолично принимать решения по всем вопросам, подлежащим ведению соответствующего Народного Комиссариата, доводя о них до сведения Коллегии.
В случае несогласия Коллегии с тем или иным решением Народного Комиссара, Коллегия, не приостанавливая исполнения решения, может обжаловать его в Совет Народных Комиссаров или в Президиум Всероссийского Центрального Исполнительного Комитета Советов.

То же право обжалования принадлежит и отдельным членам Коллегии.

===== Статья 46

Совет Народных Комиссаров всецело ответственен перед Всероссийским Съездом Советов и Всероссийским Центральным Исполнительным Комитетом Советов.

===== Статья 47

Народные Комиссары и Коллегии при Народных Комиссариатах всецело ответственны перед Советом Народных Комиссаров и перед Всероссийским Центральным Исполнительным Комитетом Советов.

===== Статья 48

Звание Народного Комиссара принадлежит исключительно членам Совета Народных Комиссаров, ведающего общими делами Российской Социалистической Федеративной Советской Республики, и никаким иным представителям Советской власти, как в центре, так и на местах присвоено быть не может.

==== Глава девятая. О предметах ведения Всероссийского Съезда Советов и Всероссийского Центрального Исполнительного Комитета Советов

===== Статья 49

Ведению Всероссийского Съезда Советов и Всероссийского Центрального Исполнительного Комитета Советов подлежат все вопросы общегосударственного значения, как-то:

. Утверждение, изменение и дополнение Конституции Российской Социалистической Федеративной Советской Республики.
. Общее руководство всей внешней и внутренней политикой Российской Социалистической Федеративной Советской Республики.
[[p-49-3]]
. Установление и изменение границ, а равно отчуждение частей территории Российской Социалистической Федеративной Советской Республики, или принадлежащих ей прав.
. Установление границ и компетенции областных Советских союзов, входящих в состав Российской Социалистической Федеративной Советской Республики, а также разрешение споров между ними.
. Принятие в состав Российской Социалистической Федеративной Советской Республики новых сочленов Советской Республики и признание выхода из Российской Федерации отдельных частей ее.
. Общее административное разделение территории Российской Социалистической Федеративной Советской Республики и утверждение областных объединений.
. Установление и изменение системы мер, весов и денег на территории Российской Социалистической Федеративной Советской Республики.
. Сношение с иностранными государствами, объявление войны и заключение мира.
[[p-49-9]]
. Заключение займов, таможенных и торговых договоров, а равно финансовых соглашений.
. Установление основ и общего плана всего народного хозяйства и отдельных его отраслей на территории Российской Социалистической Федеративной Советской Республики.
. Утверждение бюджета Российской Социалистической Федеративной Советской Республики.
. Установление общегосударственных налогов и повинностей.
. Установление основ организации вооруженных сил Российской Социалистической Федеративной Советской Республики.
. Общегосударственное законодательство, судоустройство и судопроизводство, гражданское, уголовное законодательство и пр.
. Назначение и смещение как отдельных членов Совета Народных Комиссаров, так и всего Совета Народных Комиссаров в целом, а также утверждение Председателя Совета Народных Комиссаров.
. Издание общих постановлений о приобретении и утрате прав российского гражданства и о правах иностранцев на территории Республики.
. Право амнистии, общей и частичной.

===== Статья 50

Сверх перечисленных вопросов ведению Всероссийского Съезда Советов и Всероссийского Центрального Исполнительного Комитета Советов подлежат все вопросы, которые они признают подлежащими их разрешению.

===== Статья 51

Исключительному ведению Всероссийского Съезда Советов подлежат:

. Установление, дополнение и изменение основных начал Советской Конституции.
. Ратификация мирных договоров.

===== Статья 52

Разрешение вопросов, указанных в пунктах <<p-49-3,3>> и <<p-49-9,9>> <<Статья 49,ст.49>>, предоставляется Всероссийскому Центральному Исполнительному Комитету Советов лишь при невозможности созыва Всероссийского Съезда Советов.

=== Организация Советской власти на местах

==== Глава десятая. О Съездах Советов

===== Статья 53

Съезды Советов составляются следующим образом:

. Областные - из представителей городских Советов и уездных Съездов Советов, по расчету 1 депутат на 25.000 жителей, а от городов, по 1 депутату на 5.000 избирателей, но не более 500 делегатов на всю область, - либо из представителей губернских Съездов Советов, избираемых по той же норме, если этот Съезд собирается непосредственно перед областным Съездом Советов.
. Губернские (окружные) - из представителей городских Советов и волостных Съездов Советов, по расчету 1 депутат на 10.000 жителей, а от городов, по 1 депутату на 2 тысячи избирателей, но не свыше 300 депутатов на всю губернию (округ), причем в случае созыва уездного Съезда Советов непосредственно перед губернским выборы производятся по той же норме не волостными, а уездным Съездом Советов.
. Уездные (районные) - из представителей сельских Советов, по расчету 1 депутат на 1 тысячу жителей, но не свыше 300 депутатов на весь уезд (район).
. Волостные - из представителей всех сельских Советов волости, по расчету 1 депутат на каждые 10 членов Совета.

*Примечание 1.* В уездных Съездах Советов участвуют представители Советов городов, население которых не превышает 10 тысяч человек; сельские Советы местностей, насчитывающих менее 1 тысячи человек населения, для избрания депутатов на уездный Съезд Советов объединяются.

*Примечание 2.* Сельские Советы, насчитывающие менее 10 членов, посылают на волостной Съезд Советов по 1 представителю.

===== Статья 54

Съезды Советов созываются соответствующими по территории исполнительными органами Советской власти (Исполнительными Комитетами) по усмотрению последних или по требованию Советов местностей, насчитывающих не менее 1/3 всего населения данного района, но, во всяком случае, не реже двух раз в год по области, одного раза в три месяца по губернии и уездам и одного раза в месяц по волости.

===== Статья 55

Съезд Советов (областной, губернский, уездный, волостной) избирает свой исполнительный орган - Исполнительный Комитет, число членов которого не должно превышать: а) по области и губернии - 25, б) по уезду - 20, в) по волости - 10. Исполнительный Комитет всецело ответственен перед избравшим его Съездом Советов.

===== Статья 56

В границах своего ведения Съезд Советов (областной, губернский, уездный, волостной) есть высшая в пределах данной территории власть; в период же между Съездами такой властью является Исполнительный Комитет.

==== Глава одиннадцатая. О Советах Депутатов

===== Статья 57

Советы Депутатов образуются:

. В городах - по расчету 1 депутат на каждые 1.000 человек населения, но в числе не менее 50 и не более 1 000 членов.
. В селениях (деревнях, селах, станицах, местечках, городах с населением менее 10.000 человек, аулах, хуторах и пр.) - по расчету 1 депутат на каждые 100 человек населения, но в числе не менее 3 и не более 50 депутатов на каждое селение.

Срок полномочий депутатов - 3 месяца.

*Примечание.* В тех сельских местностях, где это будет признано осуществимым, вопросы управления разрешаются общим собранием избирателей данного селения непосредственно.

===== Статья 58

Для текущей работы Совет Депутатов избирает из своей среды исполнительный орган (Исполнительный Комитет) в количестве не свыше 5 человек в селениях, а в городах по расчету 1 на каждые 50 членов, но не менее 3 и не более 15 (Петербург и Москва не более 40).

Исполнительный Комитет всецело ответственен перед избравшим его Советом.

===== Статья 59

Совет Депутатов созывается Исполнительным Комитетом по усмотрению последнего или по требованию не менее половины членов Совета, но не реже 1 раза в неделю в городах и 2 раз в неделю в селениях.

===== Статья 60

В границах своего ведения Совет, а в случае, предусмотренном в <<Статья 57,ст.57 (примечание)>>, общее собрание избирателей есть высшая в пределах данной территории власть.

==== Глава двенадцатая. О предметах ведения органов советской власти на местах

===== Статья 61

Областные, губернские, уездные и волостные органы Советской власти, а также Советы Депутатов имеют предметом своей деятельности:

. проведение в жизнь всех постановлений соответствующих высших органов Советской власти;
. принятие всех мер к поднятию данной территории в культурном и хозяйственном отношениях;
. разрешение всех вопросов, имеющих чисто местное (для данной территории) значение;
. объединение всей Советской деятельности в пределах данной территории.

===== Статья 62

Съездам Советов и их Исполнительным Комитетам принадлежит право контроля над деятельностью местных Советов (т.-е. областным - право контроля над всеми Советами данной области, губернским - над всеми Советами данной губернии, кроме городских, не входящих в состав уездных Съездов Советов, и т.д.), а областным и губернским Съездам Советов и их Исполнительным Комитетам - кроме того, право отмены решений действующих в их районе Советов, с извещением об этом в важнейших случаях Центральной Советской власти.

===== Статья 63

Для выполнения возложенных на органы Советской власти задач при Советах (городских и сельских) и Исполнительных Комитетах (областных, губернских, уездных и волостных) образуются соответствующие отделы во главе с заведывающими отделами.

== Раздел четвертый. Активное и пассивное избирательное право

=== Глава тринадцатая

==== Статья 64

Правом избирать и быть избранными в Советы пользуются, независимо от вероисповедания, национальности, оседлости и т.п., следующие обоего пола граждане Российской Социалистической Федеративной Советской Республики, коим ко дню выборов исполнилось восемнадцать лет:

[[p-64-1]]
. все добывающие средства к жизни производительным и общественно полезным трудом, а также лица, занятые домашним хозяйством, обеспечивающим для первых возможность производительного труда, как-то: рабочие и служащие всех видов и категорий, занятые в промышленности, торговле, сельском хозяйстве и проч., крестьяне и казаки-земледельцы, не пользующиеся наемным трудом с целью извлечения прибыли.
[[p-64-2]]
. солдаты Советской армии и флота.
. граждане, входящие в категории, перечисленные в пунктах <<p-64-1,1>> и <<p-64-2,2>> настоящей статьи, потерявшие в какой-нибудь мере трудоспособность.

*Примечание 1.* Местные Советы могут с утверждения Центральной власти понижать установленную в настоящей статье возрастную норму.

*Примечание 2.* Из лиц, не вступивших в число российских граждан, пользуются активным и пассивным избирательным правом также лица, указанные в <<Статья 20,ст.20>>.

==== Статья 65

Не избирают и не могут быть избранными, хотя бы они входили в одну из вышеперечисленных категорий:

. лица, прибегающие к наемному труду с целью извлечения прибыли;
. лица, живущие на нетрудовой доход, как-то проценты с капитала, доходы с предприятий, поступления с имущества и т.п.;
. частные торговцы, торговые и коммерческие посредники;
. монахи и духовные служители церквей и религиозных культов;
. служащие и агенты бывшей полиции, особого корпуса жандармов и охранных отделений, а также члены царствовавшего в России дома;
. лица, признанные в установленном порядке душевнобольными или умалишенными, а равно лица, состоящие под опекой:
. лица, осужденные за корыстные и порочащие преступления на срок, установленный законом или судебным приговором.

=== Глава четырнадцатая. О производстве выборов

==== Cтатья 66

Выборы производятся согласно установившимся обычаям, в дни, устанавливаемые местными Советами.

==== Cтатья 67

Выборы производятся в присутствии избирательной комиссии и представителя местного Совета.

==== Cтатья 68

В тех случаях, когда присутствие представителя Советской власти оказывается технически невозможным, его заменяет председатель избирательной комиссии, а за отсутствием такового - председатель избирательного собрания.

==== Cтатья 69

О ходе и результате выборов составляется протокол за подписью членов избирательной комиссии и представителя Совета.

==== Cтатья 70

Подробный порядок производства выборов, а равно участие в них профессиональных и иных рабочих организаций определяется местными Советами согласно инструкции Всероссийского Центрального Исполнительного Комитета Советов.

=== Глава пятнадцатая. О проверке и отмене выборов и об отзыве депутатов

==== Статья 71

Весь материал по производству выборов поступает в соответственный Совет.

==== Статья 72

Совет для проверки выборов назначает мандатную комиссию.

==== Статья 73

О результатах проверки мандатная комиссия докладывает Совету.

==== Статья 74

Совет решает вопрос об утверждении спорных кандидатов.

==== Статья 75

В случае неутверждения того или иного кандидата Совет назначает новые выборы.

==== Статья 76

В случае неправильности выборов в целом - вопрос об отмене выборов разрешается высшим по порядку органом Советской власти.

==== Статья 77

Последней инстанцией по кассации Советских выборов является Всероссийский Центральный Исполнительный Комитет Советов.

==== Статья 78

Избиратели, пославшие в Совет депутата, имеют право во всякое время отозвать его и произвести новые выборы согласно общему положению.

== Раздел пятый. Бюджетное право

=== Глава шестнадцатая

==== Статья 79

Финансовая политика Российской Социалистической Федеративной Советской Республики в настоящий переходный момент диктатуры трудящихся способствует основной цели экспроприации буржуазии и подготовления условий для всеобщего равенства граждан Республики в области производства и распределения богатств.
В этих целях она ставит себе задачей предоставить в распоряжение органов Советской власти все необходимые средства для удовлетворения местных и общегосударственных нужд Советской Республики, не останавливаясь перед вторжением в право частной собственности.

==== Статья 80

Государственные доходы и расходы Российской Социалистической Федеративной Советской Республики объединяются в общегосударственном бюджете.

==== Статья 81

Всероссийский Съезд Советов или Всероссийский Центральный Исполнительный Комитет Советов определяют, какие виды доходов и сборов входят в общегосударственный бюджет и какие поступают в распоряжение местных Советов, а равно устанавливают пределы обложения.

==== Статья 82

Советы устанавливают обложение налогами и сборами исключительно на нужды местного хозяйства.
Потребности общегосударственные удовлетворяются за счет средств, отпускаемых из Государственного Казначейства.

==== Статья 83

Ни один расход из средств Государственного Казначейства не может быть произведен без установления на него кредита в росписи государственных доходов и расходов или путем издания особого постановления Центральной власти.

==== Статья 84

На удовлетворение потребностей, имеющих общегосударственное значение, в распоряжение местных Советов предоставляются подлежащими Народными Комиссариатами необходимые кредиты из Государственного Казначейства.

==== Статья 85

Все предоставленные Советам кредиты из средств Государственного Казначейства, а равно кредиты, утвержденные по сметам на местные нужды, расходуются ими в пределах сметных подразделений (параграфы и статьи) по прямому назначению и не могут быть обращаемы на удовлетворение каких-либо других потребностей без особого постановления Всероссийского Центрального Исполнительного Комитета Советов и Совета Народных Комиссаров.

==== Статья 86

Местные Советы составляют полугодовые и годовые сметы доходов и расходов на местные нужды.
Сметы сельских и волостных Советов и Советов городов, участвующих в уездных Съездах Советов, а также сметы уездных органов Советской власти утверждаются соответственно губернскими и областными Съездами Советов или их Исполнительными Комитетами; сметы городских, губернских и областных органов Советской власти утверждаются Всероссийским Центральным Исполнительным Комитетом Советов и Советом Народных Комиссаров.

==== Статья 87

На расходы, не предусмотренные сметами, а также в случае недостаточности сметных назначений дополнительные кредиты Советы испрашивают у подлежащих народных комиссариатов.

==== Статья 88

В случае недостаточности местных средств для удовлетворения местных потребностей, необходимые для покрытия неотложных расходов пособия или ссуды из средств Государственного Казначейства местным Советам разрешаются Всероссийским Центральным Исполнительным Комитетом Советов и Советом Народных Комиссаров.

== Раздел шестой. О гербе и флаге Российской Социалистической Федеративной Советской Республики

=== Глава семнадцатая

==== Статья 89

Герб Российской Социалистической Федеративной Советской Республики состоит из изображений на красном фоне в лучах солнца золотых серпа и молота, помещенных крест-на-крест рукоятками книзу, окруженных венцом из колосьев и с надписью:

. Российская Социалистическая Федеративная Советская Республика и

. Пролетарии всех стран, соединяйтесь!

==== Статья 90

Торговый, морской и военный флаг Российской Социалистической Федеративной Советской Республики состоит из полотнища красного (алого) цвета, в левом углу которого - у древка, наверху, помещены золотые буквы Р.С.Ф.С.Р. или надпись: Российская Социалистическая Федеративная Советская Республика.
